### ISSUE TITLE
PHP 5.4 doesn't work OOTB?

### ISSUE THREAD

**Issue by tcopestake** [bejean/crawl-anywhere#6]
Your page claims that CA will run fine under PHP 5.4, but I get many errors relating to deprecated features (e.g. call-time pass by reference). Am I missing something?

**Comment by FireLizard** [comment]
I've got the latest version (4.0.0) of this project. But there are some errors with php <5.5.
For example:
PHP Fatal error:  Can't use function return value in write context in /opt/crawler/web/crawler/pub/ajax/content.sources.ajax.inc.php on line 1512
See [Parameters section on empty() documentation](http://php.net/manual/en/function.empty.php#refsect1-function.empty-parameters)
So I think it would be nice to update the [Pre-requisites in readme.md](https://github.com/bejean/crawl-anywhere#installation)
